# Hadolint configuration
# Dockerfile linting rules for SoC Docker Coding Convention
---
failure-threshold: warning

override:
  # === Mandatory Rules (Error) ===
  error:
    - DL3006  # Always tag the version of an image explicitly
    - DL3059  # Multiple consecutive RUN instructions
    - DL3009  # Delete apt-get lists after installing
    - DL3010  # Use COPY instead of ADD for files

  # === Optional Rules (Warning) ===
  warning:
    - DL3008  # Pin versions in apt get install
    - DL3003  # Use WORKDIR to switch directories
    - DL3025  # Use arguments JSON notation for CMD

  # === Info Level ===
  info:
    - DL3015  # Avoid additional packages with apt-get
    - DL3013  # Pin versions in pip install

trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
  - registry.access.redhat.com

label-schema:
  maintainer: text
  description: text

# === Rule to Hadolint Code Mapping ===
#
# +------------+--------+-------------------------------------------+
# | Rule ID    | DL Code| Description                               |
# +------------+--------+-------------------------------------------+
# | Docker-01-01| DL3006| Tag base image version explicitly         |
# | Docker-01-02| DL3007| Use specific tag, not :latest             |
# | Docker-01-02| DL3008| Pin versions in apt-get install           |
# | Docker-02-01| DL3059| Avoid multiple consecutive RUN            |
# | Docker-02-03| DL3009| Delete apt-get lists after installing     |
# | Docker-04-01| DL3010| Use COPY instead of ADD for files         |
# | Docker-04-02| DL3025| Use JSON notation for CMD/ENTRYPOINT      |
# | Docker-04-03| DL3002| Last USER should not be root              |
# | Docker-05-01| DL3013| Pin versions in pip install               |
# | Docker-05-02| DL3016| Pin versions in npm install               |
# | Docker-05-03| DL3018| Pin versions in apk add                   |
# +------------+--------+-------------------------------------------+
