# yamllint configuration
# YAML linting rules for SoC YAML Coding Convention
---
extends: default

rules:
  # === Formatting Rules ===

  # YAML-01-01: 2-space indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # YAML-01-02: Max line length 100
  line-length:
    max: 100
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # YAML-01-03: No trailing whitespace
  trailing-spaces: enable

  # YAML-01-04: Newline at end of file
  new-line-at-end-of-file: enable

  # YAML-01-05: Unix line endings (LF)
  new-lines:
    type: unix

  # === Structure Rules ===

  # YAML-02-01: Consistent bracket spacing
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # YAML-02-02: Consistent brace spacing
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # YAML-02-03: Colon spacing
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # YAML-02-04: Comma spacing
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # YAML-02-05: Hyphen spacing for lists
  hyphens:
    max-spaces-after: 1

  # === Content Rules ===

  # YAML-03-01: No duplicate keys
  key-duplicates: enable

  # YAML-03-02: Key ordering (disabled)
  key-ordering: disable

  # YAML-03-03: Empty values allowed
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # YAML-03-04: Boolean consistency (true/false)
  truthy:
    level: warning
    allowed-values: ['true', 'false']
    check-keys: false

  # === Comment Rules ===

  # YAML-04-01: Space after comment hash
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  # YAML-04-02: Comment indentation
  comments-indentation: enable

  # === Document Rules ===

  # YAML-05-01: Document start marker
  document-start:
    level: warning
    present: true

  # YAML-05-02: Document end marker (disabled)
  document-end: disable

  # === Quote Rules ===

  # YAML-06-01: Quote style preference
  quoted-strings:
    quote-type: any
    required: only-when-needed

  # === Octal Rules ===

  # YAML-07-01: Explicit octal values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

ignore: |
  .git/
  .venv/
  venv/
  node_modules/
  __pycache__/

# === Rule to yamllint Code Mapping ===
#
# +------------+----------------------+--------------------------------+
# | Rule ID    | yamllint Rule        | Description                    |
# +------------+----------------------+--------------------------------+
# | YAML-01-01 | indentation          | 2-space indent                 |
# | YAML-01-02 | line-length          | Max 100 characters             |
# | YAML-01-03 | trailing-spaces      | No trailing whitespace         |
# | YAML-01-04 | new-line-at-end-of-file | Final newline               |
# | YAML-01-05 | new-lines            | Unix line endings              |
# | YAML-02-01 | brackets             | Bracket spacing                |
# | YAML-02-02 | braces               | Brace spacing                  |
# | YAML-02-03 | colons               | Colon spacing                  |
# | YAML-02-04 | commas               | Comma spacing                  |
# | YAML-02-05 | hyphens              | List hyphen spacing            |
# | YAML-03-01 | key-duplicates       | No duplicate keys              |
# | YAML-03-04 | truthy               | Boolean consistency            |
# | YAML-04-01 | comments             | Comment formatting             |
# | YAML-05-01 | document-start       | Document start marker          |
# | YAML-06-01 | quoted-strings       | Quote style                    |
# | YAML-07-01 | octal-values         | Octal value format             |
# +------------+----------------------+--------------------------------+
